package com.enuoai.soa.agent.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2015-12-25T10:45:34.886+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://controller.agent.soa.enuoai.com/", name = "AgentController")
@XmlSeeAlso({ObjectFactory.class})
public interface AgentController {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "settleAccount", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.SettleAccount")
    @WebMethod
    @ResponseWrapper(localName = "settleAccountResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.SettleAccountResponse")
    public com.enuoai.soa.agent.controller.AccountResult settleAccount(
        @WebParam(name = "accountParam", targetNamespace = "")
        com.enuoai.soa.agent.controller.AccountParam accountParam
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryAgentInfo101", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.QueryAgentInfo101")
    @WebMethod
    @ResponseWrapper(localName = "queryAgentInfo101Response", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.QueryAgentInfo101Response")
    public com.enuoai.soa.agent.controller.AgentInfoResult queryAgentInfo101(
        @WebParam(name = "loginUserId", targetNamespace = "")
        java.lang.String loginUserId
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "registerAgent", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.RegisterAgent")
    @WebMethod
    @ResponseWrapper(localName = "registerAgentResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.RegisterAgentResponse")
    public com.enuoai.soa.agent.controller.AgentResult registerAgent(
        @WebParam(name = "soaUserPasswordTokenVo", targetNamespace = "")
        com.enuoai.soa.agent.controller.SoaUserPasswordToken soaUserPasswordTokenVo,
        @WebParam(name = "agentInfo", targetNamespace = "")
        com.enuoai.soa.agent.controller.AgentInfoVo agentInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getCommissionDetails", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.GetCommissionDetails")
    @WebMethod
    @ResponseWrapper(localName = "getCommissionDetailsResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.GetCommissionDetailsResponse")
    public com.enuoai.soa.agent.controller.CommissionDetailResult getCommissionDetails(
        @WebParam(name = "commissionDetailsParm", targetNamespace = "")
        com.enuoai.soa.agent.controller.CommissionDetailsParm commissionDetailsParm
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getCommission", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.GetCommission")
    @WebMethod
    @ResponseWrapper(localName = "getCommissionResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.GetCommissionResponse")
    public com.enuoai.soa.agent.controller.CommissionDataResult getCommission(
        @WebParam(name = "commissionParm", targetNamespace = "")
        com.enuoai.soa.agent.controller.CommissionParm commissionParm
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryAgentStatus", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.QueryAgentStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryAgentStatusResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.QueryAgentStatusResponse")
    public com.enuoai.soa.agent.controller.AgentStatusResult queryAgentStatus(
        @WebParam(name = "userIds", targetNamespace = "")
        java.util.List<java.lang.String> userIds
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "registerAgent101", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.RegisterAgent101")
    @WebMethod
    @ResponseWrapper(localName = "registerAgent101Response", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.RegisterAgent101Response")
    public com.enuoai.soa.agent.controller.AgentResult101 registerAgent101(
        @WebParam(name = "agentInfo", targetNamespace = "")
        com.enuoai.soa.agent.controller.AgentInfo101 agentInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryAgentInfo", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.QueryAgentInfo")
    @WebMethod
    @ResponseWrapper(localName = "queryAgentInfoResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.QueryAgentInfoResponse")
    public com.enuoai.soa.agent.controller.AgentResult queryAgentInfo(
        @WebParam(name = "loginUserID", targetNamespace = "")
        java.lang.String loginUserID
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateAgentInfo101", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.UpdateAgentInfo101")
    @WebMethod
    @ResponseWrapper(localName = "updateAgentInfo101Response", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.UpdateAgentInfo101Response")
    public com.enuoai.soa.agent.controller.AgentResult101 updateAgentInfo101(
        @WebParam(name = "agentInfo", targetNamespace = "")
        com.enuoai.soa.agent.controller.AgentInfo101 agentInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "uploadAgentFaceImg", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.UploadAgentFaceImg")
    @WebMethod
    @ResponseWrapper(localName = "uploadAgentFaceImgResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.UploadAgentFaceImgResponse")
    public com.enuoai.soa.agent.controller.Result uploadAgentFaceImg(
        @WebParam(name = "agentFaceImgParam", targetNamespace = "")
        com.enuoai.soa.agent.controller.AgentFaceImgParam agentFaceImgParam
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateAgentInfo", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.UpdateAgentInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateAgentInfoResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.UpdateAgentInfoResponse")
    public com.enuoai.soa.agent.controller.AgentResult updateAgentInfo(
        @WebParam(name = "loginUserID", targetNamespace = "")
        java.lang.String loginUserID,
        @WebParam(name = "agentInfo", targetNamespace = "")
        com.enuoai.soa.agent.controller.AgentInfoVo agentInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getRenewList", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.GetRenewList")
    @WebMethod
    @ResponseWrapper(localName = "getRenewListResponse", targetNamespace = "http://controller.agent.soa.enuoai.com/", className = "com.enuoai.soa.agent.controller.GetRenewListResponse")
    public com.enuoai.soa.agent.controller.RenewResult getRenewList(
        @WebParam(name = "renewParam", targetNamespace = "")
        com.enuoai.soa.agent.controller.RenewParam renewParam
    );
}
